### PR TITLE
Milestone 1: Prepare data architecture documentation

### PR DESCRIPTION
**Pull request by shjang7**
We have drawn Entity Relationship Diagram.
Please review our ERD.
Thanks.

### CODE REVIEW

**Comment by shjang7** [comment]
Thanks @JamesOkunlade,
We understood that 'User', 'Friendship' and 'User' should be 1 : n : 1 connection since 'Friendship' is an 'intersect entity'.

But I disagree that 'zero or many' relationship should be changed for 'one or many'.
Because 'one or many' is for mandatory required entity, and 'zero or many' is for optionally required entity through this video explanation. https://www.youtube.com/watch?v=-fQ-bRllhXc 
it is the reason below, 
an 'user' can have 'post(0~many)', 'liked post(0~many), 'comment(0~many)', 'friendship(0~many) in the facebook I mean'
a 'post' can have 'comment(0~many)', 'liked post(0~many)' 

Literally we can say 'has many' in rails seems closer with 'one or many' instead of 'zero or many'. But it is crystal clear that we are going to implement 'zero or many' to the rails 'has many'. 
If you provide us any back up material why we should change 'zero or many' to 'one or many', we can learn and correct it.
Thank you.

**Comment by JamesOkunlade** [comment]
First, look at the types of Rails association we have 

image
 
Read this to understand `has many` is actually `zero or many` in the rails.

image

You ERD is correct but there's no implementation for `zero or many` so not to confuse you moving forward it's best you use `has many`. 

Reach out to me on slack if you have more questions :slightly_smiling_face:

**Comment by shjang7** [comment]
@JamesOkunlade OK, I understand.
OK, I make sure not to confuse about it for implementation.
Thanks.

**Comment by JamesOkunlade** [comment]
Well then. :grin:

**Comment by shjang7** [comment]
Thanks for review the code @JamesOkunlade @mcrd25 ,
Me and my partner discussed together for drawing this architecture.
Thanks.

**Pull request merged**
